# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: あそびば32
email: journey.b.goode__at__gmail.com
description: >+ # this means to ignore newlines until "baseurl:"
  ここはあそびば。
  つくってはこわし、つくってはこわし。
url: "https://bbq-all-stars.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bbq_all_stars
github_username:  bbq-all-stars
author: Shun Tabata
header_pages:
  - resume.md
  - links.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# NOTE: not whitelisted in github pages: https://github.com/github/pages-gem/pull/119
#  - jekyll-last-modified-at

minima:
  date_format: "%Y/%b./%-d"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
